#! /bin/bash


print_music() {
    artist=$(mpc current -f %artist%)
    track=$(mpc current -f %title%)
    status=$(mpc status | sed -n 2p | awk '{print $1;}')
    
    if [ "$status" = "[playing]" ]; then
        echo -ne "^b#1c1c1c^^c#98971a^ ▶ ${track} - ${artist}"
    else
        echo -ne "^b#1c1c1c^^c#d65d0e^ ⏸ ${track} - ${artist}"
    fi
}


print_volume() {

    muted=$(pulsemixer --get-mute)
    vol=$(pulsemixer --get-volume | awk '{print $1}')

    if [ $muted -eq 1 ]; then
        echo -ne "^b#1c1c1c^^c#d65d0e^ 🔇 ${vol}%"
    else
        echo -ne "^b#1c1c1c^^c#83a598^ 🔈 ${vol}%"
    fi

}


print_wifi() {
    WLAN=$(ip --brief a show wlp1s0 | awk '{print $2}')

    case $WLAN in 
            "DOWN")
                echo -ne "^b#1c1c1c^^c#d65d0e^ DOWN";;
            "UP")

                    SSID=$(iw wlp1s0 info |awk '/^\tssid/ {print $2}')
                    if [ -z $SSID ]; then
                            wlan_status="UP"
                    else
                            wlan_status=$(echo "$SSID" |cut -c 1-10)
                    fi
                    echo -ne "^b#1c1c1c^^c#fabd2f^ ${wlan_status}";;
    esac

}



print_ram() {
    mem=$(free -h | awk '/^Mem:/ {print $3}')
    echo -ne "^b#1c1c1c^^c#8ec07c^ ${mem}"
}

print_power() {

    status="$(cat /sys/class/power_supply/AC/online)"
    battery="$(cat /sys/class/power_supply/BAT0/capacity)"
    timer="$(acpi -b | grep "Battery" | awk '{print $5}' | cut -c 1-5)"

    if [[ "${battery}" -le 5 ]]; then
        notify-send -u critical "Low battery ${battery}% (${timer} left)"
    fi

    if [ "${status}" == 1 ]; then # Charging
        echo -ne "^b#1c1c1c^^c#83a598^ ${battery}% ${timer}"
    else # Discharging
        if [[ "${battery}" < 15 ]]; then
            echo -ne "^b#1c1c1c^^c#cc241d^ ${battery}% ${timer}"
        else
            echo -ne "^b#1c1c1c^^c#d65d0e^ ${battery}% ${timer}"
        fi
    fi
}

print_date() {
    time_status=$(date "+%a %d/%m/%y - %T")
    echo -ne "^c#83a598^^b#1c1c1c^ ${time_status}"
}
while true; do
    xsetroot -name " $(print_music) $(print_volume) $(print_wifi) $(print_ram) $(print_power) $(print_date) "
    sleep 1
done

