#!/bin/bash

if [ $# -eq 0 ] || [ "$1" = "-" ]; then
	dir="$HOME/Videos/Anime/"
elif [ "$1" = "-l" ]; then
		notify-send "$(ls  $HOME/Videos/Anime/)"
		exit 0
else
	dir="$HOME/Videos/Anime/$1/"
fi

mpv "$dir$(find $dir -type f |sed "s:$dir::g" |rofi -dmenu)"
