#!/bin/bash

function usage() {
    echo "A small utility script to set a binary in path quickly."
    echo "Usage : [sudo] myln <file> <binary_name>"
}

if [ "$#" -ne 2 ]; then
    usage 
    exit 1
fi

if [ "$EUID" -ne 0 ];then 
    echo "Please run as root."
    exit
fi

ln -s "$(pwd)/$1" /usr/local/bin/$2
