#!/bin/bash

if [ -z $1 ]; then
    brightness=0.75
else
    brightness=$1
fi

while IFS= read -r line 
do
    screen=$(echo $line |awk '{print $1}')
    xrandr --output $screen --brightness $brightness
done <<< $(xrandr -q |grep " connected")