#!/bin/bash

if [ "$PC" = "laptop" ]; then
    pic_path="~/d/Pictures/Screenshots"
else
    pic_pat="~/Pictures/Screenshots"
fi

if [ "$1" = "-s" ]; then
    scrot -s -e '/usr/bin/xclip -sel clip -target image/png $f && mv $f $pic_path'
else
    scrot -e '/usr/bin/xclip -sel clip -target image/png $f && mv $f $pic_path' --delay 1
fi 
