#!/usr/bin/env python

import eyeD3
import argparse

def check_args():
    parser = argparse.ArgumentParser(description='MP3 tagging script.')

    parser.add_argument("-ar", "--artist",
                    help="The artist/band to set",
                    type=str)

    parser.add_argument("-th", "--thumbnail",
                    help="A thumbnail image to set as artwork",
                    type=open)

    parser.add_argument("-al", "--album",
                    help="An album to set",
                    type=str)

    parser.add_argument("-ti", "--title",
                    help="The title to set",
                    type=str)

    parser.add_argument("-i", "--in",
                    help="The file to tag, or the directory to search recursively for files to tag.",
                    type=str,
                    required=True)

    parser.add_argument("-v" ,"--verbose",
                    help="Set verbosity on.",
                    action="store_true")

    return parser.parse_args()


if __name__ == "__main__":
    args = check_args()
    print(args)
